name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
